[package]
name = "rust-fe"
version = "0.1.0"
description = "ğŸ¦€ Rust in front-end (ç³»åˆ—æ•™ç¨‹ - ç”¨å‰ç«¯è§†è§’å­¦ä¹  Rust)"
authors = ["lencx <cxin1314@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
